"""Installed-app discovery: Start Menu shortcuts + UWP apps, aliases, browser.

data/apps.json:
    {"scanned_at": 0.0, "browser": "default",
     "aliases": {"wa": "WhatsApp"},
     "apps": [{"name": "Google Chrome", "kind": "app",
               "target": "C:\\...\\chrome.exe", "args": ""}]}
"""
from __future__ import annotations

import json
import re
import subprocess
import threading
import time
from difflib import SequenceMatcher
from pathlib import Path
from typing import Any

from .config import DATA_DIR

APPS_PATH = DATA_DIR / "apps.json"
BROWSERS = ("default", "chrome", "brave", "edge")
MAX_AGE = 7 * 24 * 3600  # re-scan weekly

_LOCK = threading.Lock()
_EMPTY: dict[str, Any] = {"scanned_at": 0.0, "browser": "default", "aliases": {}, "apps": []}
_SCANNING = False

# One PowerShell pass: every Start Menu .lnk (all users + current user), then
# Get-StartApps for Store/UWP apps. Run by Mot itself, never from model output.
_PS_SCRIPT = r"""
$ErrorActionPreference='SilentlyContinue'
$rows=@()
$sh=New-Object -ComObject WScript.Shell
foreach($root in @("$env:ProgramData\Microsoft\Windows\Start Menu\Programs",
                    "$env:APPDATA\Microsoft\Windows\Start Menu\Programs")){
  if(Test-Path -LiteralPath $root){
    Get-ChildItem -LiteralPath $root -Recurse -Filter *.lnk -File | ForEach-Object {
      $s=$sh.CreateShortcut($_.FullName)
      if($s.TargetPath){
        $rows += [pscustomobject]@{name=$_.BaseName; kind='app'; target=$s.TargetPath; args=$s.Arguments}
      }
    }
  }
}
Get-StartApps | ForEach-Object {
  $id=$_.AppID
  if($id -and $id -notlike 'Microsoft.AutoGenerated*'){
    $rows += [pscustomobject]@{name=$_.Name; kind='uwp'; target=$id; args=''}
  }
}
ConvertTo-Json -InputObject $rows -Compress -Depth 3
"""


def _run_ps(script: str, timeout: float = 90.0) -> str:
    """Run a PowerShell snippet and return stdout (replaced by tests)."""
    proc = subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", script],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
    )
    if proc.returncode != 0:
        raise RuntimeError((proc.stderr or "PowerShell failed").strip()[:200])
    return proc.stdout


# --- store -----------------------------------------------------------------

def load() -> dict[str, Any]:
    with _LOCK:
        if not APPS_PATH.exists():
            return json.loads(json.dumps(_EMPTY))
        try:
            data = json.loads(APPS_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return json.loads(json.dumps(_EMPTY))
    if not isinstance(data, dict):
        return json.loads(json.dumps(_EMPTY))
    for key, default in _EMPTY.items():
        data.setdefault(key, json.loads(json.dumps(default)))
    return data


def save(data: dict[str, Any]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with _LOCK:
        APPS_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")


# --- discovery -------------------------------------------------------------

def _clean(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Dedupe by name (shortcuts win) and drop junk."""
    out: list[dict[str, Any]] = []
    seen: set[str] = set()
    for row in rows:
        name = str(row.get("name") or "").strip()
        target = str(row.get("target") or "").strip()
        if not name or not target:
            continue
        key = _norm(name)
        if key in seen:
            continue
        seen.add(key)
        out.append(
            {"name": name, "kind": "uwp" if row.get("kind") == "uwp" else "app",
             "target": target, "args": str(row.get("args") or "")}
        )
    return out


def scan() -> int:
    """Discover apps now and cache them. Returns how many were found."""
    global _SCANNING
    if _SCANNING:
        return len(load().get("apps", []))
    _SCANNING = True
    try:
        raw = _run_ps(_PS_SCRIPT)
        parsed = json.loads(raw or "[]")
        if isinstance(parsed, dict):
            parsed = [parsed]
        apps = _clean([r for r in parsed if isinstance(r, dict)])
        data = load()
        data["apps"] = apps
        data["scanned_at"] = time.time()
        save(data)
        return len(apps)
    finally:
        _SCANNING = False


def rescan_if_stale() -> None:
    """Called once at startup in a background thread."""
    if time.time() - float(load().get("scanned_at") or 0) > MAX_AGE:
        try:
            scan()
        except Exception:  # noqa: BLE001 - discovery is best effort
            pass


def list_apps() -> list[dict[str, Any]]:
    return load().get("apps", [])


def names() -> list[str]:
    return [a["name"] for a in list_apps()]


# --- aliases + preferred browser ------------------------------------------

def aliases() -> dict[str, str]:
    return dict(load().get("aliases", {}))


def set_aliases(mapping: dict[str, str]) -> dict[str, str]:
    clean = {
        _norm(k): str(v).strip()
        for k, v in (mapping or {}).items()
        if str(k).strip() and str(v).strip()
    }
    data = load()
    data["aliases"] = clean
    save(data)
    return clean


def browser() -> str:
    value = str(load().get("browser") or "default").lower()
    return value if value in BROWSERS else "default"


def set_browser(value: str) -> str:
    data = load()
    data["browser"] = value if value in BROWSERS else "default"
    save(data)
    return data["browser"]


# --- matching --------------------------------------------------------------

def _norm(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (text or "").lower())


def match(query: str) -> dict[str, Any] | None:
    """Best app for a name: alias -> exact -> contains -> fuzzy."""
    q = (query or "").strip()
    if not q:
        return None
    apps = list_apps()
    if not apps:
        return None

    alias_target = aliases().get(_norm(q))
    if alias_target:
        hit = _match_against(alias_target, apps)
        if hit:
            return hit
    return _match_against(q, apps)


def claims(name: str) -> bool:
    """True when `name` IS an app (or one of its aliases), not merely close.

    Bare segments get no verb to lean on: "whatsapp zara hi" scores 0.78
    against WhatsApp, and opening the app there would swallow a WhatsApp
    message. Those must fall through to the LLM path instead.
    """
    entry = match(name)
    if entry is None:
        return False
    want = _norm(name)
    have = _norm(str(entry.get("name") or ""))
    if not want or not have:
        return False
    if want in have:  # "wa" -> WhatsApp, "notepad" -> Notepad, "chrome" -> Google Chrome
        return True
    alias = aliases().get(want)
    return alias is not None and _norm(alias) == have


def _match_against(query: str, apps: list[dict[str, Any]]) -> dict[str, Any] | None:
    q = _norm(query)
    if not q:
        return None

    for app in apps:  # exact name, then exact exe name (chrome.exe)
        if _norm(app["name"]) == q:
            return app
    for app in apps:
        if app["kind"] == "app" and _norm(Path(app["target"]).stem) == q:
            return app

    best: dict[str, Any] | None = None
    best_score = 0.0
    for app in apps:
        name = _norm(app["name"])
        stem = _norm(Path(app["target"]).stem) if app["kind"] == "app" else ""
        score = 0.0
        if name.startswith(q) or (stem and stem.startswith(q)):
            score = 0.9
        elif q in name or (stem and q in stem):
            score = 0.75
        else:
            score = SequenceMatcher(None, q, name).ratio()
        if score > best_score and score >= 0.65:
            best, best_score = app, score
        elif score == best_score and best is not None and len(app["name"]) > len(best["name"]):
            best = app  # prefer the shorter, more standard name
    return best
